//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.talent.com/", ConfigurationName="ServiceReference1.ToZDCJWebService")]
    public interface ToZDCJWebService {
        
        // CODEGEN: 命名空间  的元素名称 equipmentname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        test.ServiceReference1.saveZlItemvalueCollectionResponse saveZlItemvalueCollection(test.ServiceReference1.saveZlItemvalueCollection request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<test.ServiceReference1.saveZlItemvalueCollectionResponse> saveZlItemvalueCollectionAsync(test.ServiceReference1.saveZlItemvalueCollection request);
        
        // CODEGEN: 命名空间  的元素名称 equipmentname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        test.ServiceReference1.getMaxCollectdateByEquipmentnameResponse getMaxCollectdateByEquipmentname(test.ServiceReference1.getMaxCollectdateByEquipmentname request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<test.ServiceReference1.getMaxCollectdateByEquipmentnameResponse> getMaxCollectdateByEquipmentnameAsync(test.ServiceReference1.getMaxCollectdateByEquipmentname request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveZlItemvalueCollection {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveZlItemvalueCollection", Namespace="http://webservice.talent.com/", Order=0)]
        public test.ServiceReference1.saveZlItemvalueCollectionBody Body;
        
        public saveZlItemvalueCollection() {
        }
        
        public saveZlItemvalueCollection(test.ServiceReference1.saveZlItemvalueCollectionBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveZlItemvalueCollectionBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string equipmentname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string itemab;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string itemvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string collectdate;
        
        public saveZlItemvalueCollectionBody() {
        }
        
        public saveZlItemvalueCollectionBody(string equipmentname, string documentno, string itemab, string itemvalue, string collectdate) {
            this.equipmentname = equipmentname;
            this.documentno = documentno;
            this.itemab = itemab;
            this.itemvalue = itemvalue;
            this.collectdate = collectdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveZlItemvalueCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveZlItemvalueCollectionResponse", Namespace="http://webservice.talent.com/", Order=0)]
        public test.ServiceReference1.saveZlItemvalueCollectionResponseBody Body;
        
        public saveZlItemvalueCollectionResponse() {
        }
        
        public saveZlItemvalueCollectionResponse(test.ServiceReference1.saveZlItemvalueCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveZlItemvalueCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveZlItemvalueCollectionResponseBody() {
        }
        
        public saveZlItemvalueCollectionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaxCollectdateByEquipmentname {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaxCollectdateByEquipmentname", Namespace="http://webservice.talent.com/", Order=0)]
        public test.ServiceReference1.getMaxCollectdateByEquipmentnameBody Body;
        
        public getMaxCollectdateByEquipmentname() {
        }
        
        public getMaxCollectdateByEquipmentname(test.ServiceReference1.getMaxCollectdateByEquipmentnameBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getMaxCollectdateByEquipmentnameBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string equipmentname;
        
        public getMaxCollectdateByEquipmentnameBody() {
        }
        
        public getMaxCollectdateByEquipmentnameBody(string equipmentname) {
            this.equipmentname = equipmentname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaxCollectdateByEquipmentnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaxCollectdateByEquipmentnameResponse", Namespace="http://webservice.talent.com/", Order=0)]
        public test.ServiceReference1.getMaxCollectdateByEquipmentnameResponseBody Body;
        
        public getMaxCollectdateByEquipmentnameResponse() {
        }
        
        public getMaxCollectdateByEquipmentnameResponse(test.ServiceReference1.getMaxCollectdateByEquipmentnameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getMaxCollectdateByEquipmentnameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getMaxCollectdateByEquipmentnameResponseBody() {
        }
        
        public getMaxCollectdateByEquipmentnameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ToZDCJWebServiceChannel : test.ServiceReference1.ToZDCJWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToZDCJWebServiceClient : System.ServiceModel.ClientBase<test.ServiceReference1.ToZDCJWebService>, test.ServiceReference1.ToZDCJWebService {
        
        public ToZDCJWebServiceClient() {
        }
        
        public ToZDCJWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToZDCJWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToZDCJWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToZDCJWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.saveZlItemvalueCollectionResponse test.ServiceReference1.ToZDCJWebService.saveZlItemvalueCollection(test.ServiceReference1.saveZlItemvalueCollection request) {
            return base.Channel.saveZlItemvalueCollection(request);
        }
        
        public string saveZlItemvalueCollection(string equipmentname, string documentno, string itemab, string itemvalue, string collectdate) {
            test.ServiceReference1.saveZlItemvalueCollection inValue = new test.ServiceReference1.saveZlItemvalueCollection();
            inValue.Body = new test.ServiceReference1.saveZlItemvalueCollectionBody();
            inValue.Body.equipmentname = equipmentname;
            inValue.Body.documentno = documentno;
            inValue.Body.itemab = itemab;
            inValue.Body.itemvalue = itemvalue;
            inValue.Body.collectdate = collectdate;
            test.ServiceReference1.saveZlItemvalueCollectionResponse retVal = ((test.ServiceReference1.ToZDCJWebService)(this)).saveZlItemvalueCollection(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.ServiceReference1.saveZlItemvalueCollectionResponse> test.ServiceReference1.ToZDCJWebService.saveZlItemvalueCollectionAsync(test.ServiceReference1.saveZlItemvalueCollection request) {
            return base.Channel.saveZlItemvalueCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.ServiceReference1.saveZlItemvalueCollectionResponse> saveZlItemvalueCollectionAsync(string equipmentname, string documentno, string itemab, string itemvalue, string collectdate) {
            test.ServiceReference1.saveZlItemvalueCollection inValue = new test.ServiceReference1.saveZlItemvalueCollection();
            inValue.Body = new test.ServiceReference1.saveZlItemvalueCollectionBody();
            inValue.Body.equipmentname = equipmentname;
            inValue.Body.documentno = documentno;
            inValue.Body.itemab = itemab;
            inValue.Body.itemvalue = itemvalue;
            inValue.Body.collectdate = collectdate;
            return ((test.ServiceReference1.ToZDCJWebService)(this)).saveZlItemvalueCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.getMaxCollectdateByEquipmentnameResponse test.ServiceReference1.ToZDCJWebService.getMaxCollectdateByEquipmentname(test.ServiceReference1.getMaxCollectdateByEquipmentname request) {
            return base.Channel.getMaxCollectdateByEquipmentname(request);
        }
        
        public string getMaxCollectdateByEquipmentname(string equipmentname) {
            test.ServiceReference1.getMaxCollectdateByEquipmentname inValue = new test.ServiceReference1.getMaxCollectdateByEquipmentname();
            inValue.Body = new test.ServiceReference1.getMaxCollectdateByEquipmentnameBody();
            inValue.Body.equipmentname = equipmentname;
            test.ServiceReference1.getMaxCollectdateByEquipmentnameResponse retVal = ((test.ServiceReference1.ToZDCJWebService)(this)).getMaxCollectdateByEquipmentname(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test.ServiceReference1.getMaxCollectdateByEquipmentnameResponse> test.ServiceReference1.ToZDCJWebService.getMaxCollectdateByEquipmentnameAsync(test.ServiceReference1.getMaxCollectdateByEquipmentname request) {
            return base.Channel.getMaxCollectdateByEquipmentnameAsync(request);
        }
        
        public System.Threading.Tasks.Task<test.ServiceReference1.getMaxCollectdateByEquipmentnameResponse> getMaxCollectdateByEquipmentnameAsync(string equipmentname) {
            test.ServiceReference1.getMaxCollectdateByEquipmentname inValue = new test.ServiceReference1.getMaxCollectdateByEquipmentname();
            inValue.Body = new test.ServiceReference1.getMaxCollectdateByEquipmentnameBody();
            inValue.Body.equipmentname = equipmentname;
            return ((test.ServiceReference1.ToZDCJWebService)(this)).getMaxCollectdateByEquipmentnameAsync(inValue);
        }
    }
}
